/** Visible marker for anything AI-generated (required until human approval). */
export function AiTag({ label = 'AI-suggested' }: { label?: string }) {
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full bg-gradient-to-r from-violet-100 to-teal-100 px-2 py-0.5 text-xs font-medium text-violet-700"
      title="This content was generated by AI and is pending human review"
    >
      ✨ {label}
    </span>
  );
}
