apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mugheer-production
resources:
  - ../../base
images:
  - name: registry.example.com/mugheer/backend-core
    newTag: production
  - name: registry.example.com/mugheer/frontend
    newTag: production
  - name: registry.example.com/mugheer/worker
    newTag: production
